name: Build and Test .NET Console App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Verify project exists  # Additional step to check if project file exists
      run: |
        if [ ! -f "MyConsoleLibrary/MyConsoleLibrary.csproj" ]; then
          echo "Project file not found!"
          exit 1
        fi

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore MyConsoleLibrary/MyConsoleLibrary.csproj  # Explicit path

    - name: Build the project
      run: dotnet build MyConsoleLibrary/MyConsoleLibrary.csproj --no-restore  # Explicit path

    - name: Run unit tests
      run: dotnet test MyConsoleLibrary/MyConsoleLibrary.csproj --no-build --verbosity normal  # Explicit path
