name: Build and Test .NET Project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Navigate to the directory where your project/solution resides
    - name: Change to project directory
      run: cd MyConsoleLibrary  # Adjust if your project is in a different folder
    
    - name: Restore dependencies
      run: dotnet restore MyConsoleLibrary.csproj  # Use the correct project file
    
    - name: Build the project
      run: dotnet build MyConsoleLibrary.csproj --no-restore  # Build specifying project
    
    - name: Run unit tests
      run: dotnet test MyConsoleLibrary.csproj --no-build --verbosity normal  # Test specifying project
